# Generated by Django 4.2.7 on 2023-12-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hair', '0002_galleryphoto_page_tag_delete_post_galleryphoto_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['-created_at'], 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='tag',
            new_name='tags',
        ),
    ]
